### ISSUE TITLE
Fix the crashes in Tips.

### ISSUE THREAD

**Issue by dreambottle** [dreambottle/R11-psp-english#5]
In short, the reason of crashes is too much text on the screen (the game has a limited buffer).

I currently see 2 ways to fix this:

- One is to rewrite and drop some text to simply make it shorter. This is a quick and simple way.

- Another, "correct" way, would be to add more pages and span text across them. However, this would require much more time for hacking the init.bin and rewriting the python script which does the patching, because the current one is relatively dumb.

**Comment by tinenmi** [comment]
I have perl script for patching init.bin from desktop R11. It allows adding new pages.

https://yadi.sk/d/gxI3h4hw3H5kDN

**Comment by dreambottle** [comment]
Solved in v. 2.0
